
services:
  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=grafana.soowcode.local
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    networks:
      - nginx_network
      - default
    
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: "udp://localhost:12201"
    #     tag: "grafana"

  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    # ports:
    #   - 9091:9090
    environment:
      - VIRTUAL_HOST=prometheus.soowcode.local
      - VIRTUAL_PORT=9090
    depends_on:
      - cadvisor
    networks:
      - nginx_network
      - default
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    # ports:
    #   - 9100:9100
    networks:
      - nginx_network
      - default
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - nginx_network
      - default
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
# oui
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - nginx_network
      - default
    restart: always

    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: "udp://localhost:12201"
    #     tag: "cadvisor"
#non pour nafa
  prometheus-blackbox:
    image: prom/blackbox-exporter
    volumes:
      - ./prometheus/config.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115
    networks:
      - nginx_network
      - default

    restart: always

  uptime-kuma:
    image: "louislam/uptime-kuma:1.11.3-alpine"
    restart: always
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001
    
    networks:
      - nginx_network
      - default

networks:
  nginx_network:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  
