services:
  app:
    image: kbosow/my-full-symfony:0.0.1  
    container_name: php_fpm_app  
    working_dir: /var/www/html  
    volumes:
      - ./app:/var/www/html
    command: ["php-fpm"]
    ports:
      - 9000:9000
      - 8010:8000
    networks:
      - app_network

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge