services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: db-mysql
    container_name: db-mysql
    #replace environment section
    env_file:
      - mysql.env
    ports:
      - 3306:3306
    networks:
      - default

  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: always
    ports:
      - 8085:8080
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_NAME}
      - VIRTUAL_PORT=8080
    networks:
      - proxy_my-network
      - default

networks:
  proxy_my-network:
    external: true
